### ISSUE TITLE
Scrapy Deploy error while building egg

### ISSUE THREAD

**Issue by NaruTo0o23** [scrapy/scrapyd-client#109]
```
Including dependencies in build from requirements.txt
Step #0 - "Build Spiders": Traceback (most recent call last):
Step #0 - "Build Spiders":   File "/opt/scrapy-build-venv/lib/python3.8/site-packages/scrapyd_client/cli.py", line 70, in main
Step #0 - "Build Spiders":     args.action(args)
Step #0 - "Build Spiders":   File "/opt/scrapy-build-venv/lib/python3.8/site-packages/scrapyd_client/commands.py", line 16, in deploy
Step #0 - "Build Spiders":     deploy.main()
Step #0 - "Build Spiders":   File "/opt/scrapy-build-venv/lib/python3.8/site-packages/scrapyd_client/deploy.py", line 93, in main
Step #0 - "Build Spiders":     egg, tmpdir = _build_egg(opts)
Step #0 - "Build Spiders":   File "/opt/scrapy-build-venv/lib/python3.8/site-packages/scrapyd_client/deploy.py", line 277, in _build_egg
Step #0 - "Build Spiders":     retry_on_eintr(check_call, args,stdout=o, stderr=e)
Step #0 - "Build Spiders":   File "/opt/scrapy-build-venv/lib/python3.8/site-packages/scrapyd_client/utils.py", line 73, in retry_on_eintr
Step #0 - "Build Spiders":     return function(*args, **kw)
Step #0 - "Build Spiders":   File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
Step #0 - "Build Spiders":     raise CalledProcessError(retcode, cmd)
Step #0 - "Build Spiders": subprocess.CalledProcessError: Command '['/opt/scrapy-build-venv/bin/python3', 'setup.py', 'bdist_uberegg', '-d', '/tmp/scrapydeploy-30gz2uvz']' returned non-zero exit status 1.
Step #0 - "Build Spiders": Caught unhandled exception, please report at https://github.com/scrapy/scrapyd-client/issues
```

**Comment by NaruTo0o23** [comment]
Someone Help me what should I do to resolve this

**Comment by jpmckinney** [comment]
Is this the full output?

**Comment by jpmckinney** [comment]
Closing as no response.
