### ISSUE TITLE
Scrapyd issue while starting deploy

### ISSUE THREAD

**Issue by Parikshit-DartCoder** [scrapy/scrapyd-client#119]
Stats:

**I start Scrapyd in env:**

```
(env) sh-3.2$ scrapyd
2023-01-18T14:44:21+0400 [-] Loading /Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/lib/python3.8/site-packages/scrapyd/txapp.py...
2023-01-18T14:44:21+0400 [-] Basic authentication disabled as either `username` or `password` is unset
2023-01-18T14:44:21+0400 [-] Scrapyd web console available at http://127.0.0.1:6800/
2023-01-18T14:44:21+0400 [-] Loaded.
2023-01-18T14:44:21+0400 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 22.10.0 (/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/bin/python3 3.8.9) starting up.
2023-01-18T14:44:21+0400 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.selectreactor.SelectReactor.
2023-01-18T14:44:21+0400 [-] Site starting on 6800
2023-01-18T14:44:21+0400 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site object at 0x10766ed90>
2023-01-18T14:44:21+0400 [Launcher] Scrapyd 1.3.0 started: max_proc=48, runner='scrapyd.runner'
```

**I try running scraped-deploy local**

But I get these errors

```
(env) pmukherjee0l-3:ufc-data-crawler parikshit.mukherjee$ scrapyd-deploy local
Packing version 1674038954
Traceback (most recent call last):
  File "/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/bin/scrapyd-deploy", line 8, in <module>
    sys.exit(main())
  File "/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/lib/python3.8/site-packages/scrapyd_client/deploy.py", line 106, in main
    exitcode, tmpdir = _build_egg_and_deploy_target(target, version, opts)
  File "/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/lib/python3.8/site-packages/scrapyd_client/deploy.py", line 130, in _build_egg_and_deploy_target
    egg, tmpdir = _build_egg(opts)
  File "/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/lib/python3.8/site-packages/scrapyd_client/deploy.py", line 276, in _build_egg
    retry_on_eintr(check_call, [sys.executable, 'setup.py', 'clean', '-a', command, '-d', d], stdout=o, stderr=e)
  File "/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/lib/python3.8/site-packages/scrapyd_client/utils.py", line 73, in retry_on_eintr
    return function(*args, **kw)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Users/parikshit.mukherjee/PycharmProjects/nn/ufc-data-crawler/env/bin/python3', 'setup.py', 'clean', '-a', 'bdist_egg', '-d', '/var/folders/vr/xn3bff3j17n4jhly7sb0tct00000gp/T/scrapydeploy-nb0ivw38']' returned non-zero exit status 1.
```
Scrapy version 1.3.0, Python 3.8

**Comment by mxdev88** [comment]
what's in your `scrapy.cfg`? what version of `scrapyd-client`?

**Comment by jpmckinney** [comment]
One way to reproduce this error is to uninstall uberegg.

The files in the temporary directory mentioned in the last line of the output (e.g. `/var/folders/vr/xn3bff3j17n4jhly7sb0tct00000gp/T/scrapydeploy-nb0ivw38`) should contain stdout and stderr with more info.
