### ISSUE TITLE
builtins.NotADirectoryError:

### ISSUE THREAD

**Issue by tubutafeng** [scrapy/scrapyd-client#59]
Traceback (most recent call last):
	  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/crawler.py", line 172, in crawl
	    return self._crawl(crawler, *args, **kwargs)
	  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/crawler.py", line 176, in _crawl
	    d = crawler.crawl(*args, **kwargs)
	  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/defer.py", line 1613, in unwindGenerator
	    return _cancellableInlineCallbacks(gen)
	  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/defer.py", line 1529, in _cancellableInlineCallbacks
	    _inlineCallbacks(None, g, status)
	--- <exception caught here> ---
	  File "/usr/local/python3/lib/python3.7/site-packages/Twisted-18.9.0-py3.7-linux-x86_64.egg/twisted/internet/defer.py", line 1418, in _inlineCallbacks
	    result = g.send(result)
	  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/crawler.py", line 79, in crawl
	    self.spider = self._create_spider(*args, **kwargs)
	  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/crawler.py", line 102, in _create_spider
	    return self.spidercls.from_crawler(self, *args, **kwargs)
	  File "/usr/local/python3/lib/python3.7/site-packages/scrapy/spiders/__init__.py", line 51, in from_crawler
	    spider = cls(*args, **kwargs)
	  File "/tmp/firstSpider-1557370240-euy4radb.egg/firstSpider/spiders/test.py", line 19, in __init__

	builtins.NotADirectoryError: [Errno 20] Not a directory: '/tmp/firstSpider-1557370240-euy4radb.egg/firstSpider/spiders'

**Comment by Digenis** [comment]
@tubutafeng, see https://github.com/scrapy/scrapyd-client/issues/46
Do you try to open a file using `__file__`?

**Comment by jpmckinney** [comment]
The traceback does not contain any reference to scrapyd-client. This seems like a Scrapy issue. See the support channels her: https://scrapy.org/community/ I would recommend sharing the `test.py` file, as otherwise, it is not possible to debug.
