### ISSUE TITLE
import scrapy to change scrapy frame

### ISSUE THREAD

**Issue by monamiiKe** [scrapy/scrapyd-client#64]
I use scrapy but not frame，then when I chage it to frame and deploy my project,I meet a question.

1. scrapy list is well.but when I scrapyd-deploy can not deploy my
` "status": "error", "message": "Traceback (most recent call last):\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\runpy.py\", line 193, in _run_module_as_main\r\n    \"__main__\", mod_spec)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\
runpy.py\", line 85, in _run_code\r\n    exec(code, run_globals)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapyd\\runner.py\", line 40, in <module>\r\n    main()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapyd\\runner.py\", l
ine 37, in main\r\n    execute()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\cmdline.py\", line 149, in execute\r\n    cmd.crawler_process = CrawlerProcess(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler
.py\", line 251, in __init__\r\n    super(CrawlerProcess, self).__init__(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler.py\", line 137, in __init__\r\n    self.spider_loader = _get_spider_loader(settings)\r\n  File \"C:\\Progr
amData\\Anaconda3\\lib\\site-packages\\scrapy\\crawler.py\", line 338, in _get_spider_loader\r\n    return loader_cls.from_settings(settings.frozencopy())\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 61, in from_settin
gs\r\n    return cls(settings)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 25, in __init__\r\n    self._load_all_spiders()\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\spiderloader.py\", line 47
, in _load_all_spiders\r\n    for module in walk_modules(name):\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\site-packages\\scrapy\\utils\\misc.py\", line 71, in walk_modules\r\n    submod = import_module(fullpath)\r\n  File \"C:\\ProgramData\\Anaconda3\\lib\\impor
tlib\\__init__.py\", line 127, in import_module\r\n    return _bootstrap._gcd_import(name[level:], package, level)\r\n  File \"<frozen importlib._bootstrap>\", line 1006, in _gcd_import\r\n  File \"<frozen importlib._bootstrap>\", line 983, in _find_and_load\r\n  F
ile \"<frozen importlib._bootstrap>\", line 967, in _find_and_load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 668, in _load_unlocked\r\n  File \"<frozen importlib._bootstrap>\", line 638, in _load_backward_compatible\r\n  File \"c:\\users\\admini~1\
\appdata\\local\\temp\\monamii_rfq-1584953814-kcde39hb.egg\\scrapyrfq\\spiders\\rfq.py\", line 27, in <module>\r\nModuleNotFoundError: No module named 'webhook'\r\n"`

**Comment by jpmckinney** [comment]
Cleaning up the traceback:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapyd\runner.py", line 40, in <module>
    main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapyd\runner.py", line 37, in main
    execute()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\cmdline.py", line 149, in execute
    cmd.crawler_process = CrawlerProcess(settings)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 251, in __init__
    super(CrawlerProcess, self).__init__(settings)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 137, in __init__
    self.spider_loader = _get_spider_loader(settings)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\crawler.py", line 338, in _get_spider_loader
    return loader_cls.from_settings(settings.frozencopy())
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\spiderloader.py", line 61, in from_settings
    return cls(settings)
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\spiderloader.py", line 25, in __init__
    self._load_all_spiders()
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\spiderloader.py", line 47, in _load_all_spiders
    for module in walk_modules(name):
  File "C:\ProgramData\Anaconda3\lib\site-packages\scrapy\utils\misc.py", line 71, in walk_modules
    submod = import_module(fullpath)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "c:\users\admini~1\appdata\local\temp\monamii_rfq-1584953814-kcde39hb.egg\scrapyrfq\spiders\rfq.py", line 27, in <module>
ModuleNotFoundError: No module named 'webhook'
```

So, there is a `scrapyfrq/spiders/rfq.py` file that is importing `webhook`, but the module doesn't exist. You probably need to install that missing module wherever your scrapyd instance is running.

**Comment by jpmckinney** [comment]
Noting that bundling dependencies into the egg is discussed in #79
