### ISSUE TITLE
chardet assertion error!

### ISSUE THREAD

**Issue by rvogel** [scrapy/scrapyd-client#74]
Running $ scrapyd-client projects gives me this:

```
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.25.8) or chardet (4.0.0) 
doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Caught unhandled exception, please report at https://github.com/scrapy/scrapyd-client/issues
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/scrapyd_client/cli.py", line 69, in main
    args.action(args)
  File "/usr/local/lib/python3.8/dist-packages/scrapyd_client/commands.py", line 21, in projects
    _projects = lib.get_projects(args.target)
  File "/usr/local/lib/python3.8/dist-packages/scrapyd_client/lib.py", line 15, in get_projects
    response = get_request(url + '/listprojects.json')
  File "/usr/local/lib/python3.8/dist-packages/scrapyd_client/utils.py", line 85, in get_request
    return _process_response(response)
  File "/usr/local/lib/python3.8/dist-packages/scrapyd_client/utils.py", line 60, in _process_response
    response = response.json()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 888, in json
    return complexjson.loads(
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

My chardet version is "4.0.0"  it seems that's the reason.  I suggest update the assert, or should I downgrade my chardet?

**Comment by jpmckinney** [comment]
scrapyd-client sets no version requirement on `requests`, and it doesn't require urllib3 or chardet. So, this is not a scrapyd-client issue. That said, I suggest running `pip install --upgrade chardet requests urllib3`.
