### ISSUE TITLE
ModuleNotFoundError: No module named 'scrapy.utils.http'

### ISSUE THREAD

**Issue by grupoz** [scrapy/scrapyd-client#78]
pip install git+https://github.com/scrapy/scrapyd-client

```
scrapyd-deploy 
Traceback (most recent call last):
  File "/home/zaterio/proyectos/isp/python3/bin/scrapyd-deploy", line 33, in <module>
    sys.exit(load_entry_point('scrapyd-client==1.2.0a1', 'console_scripts', 'scrapyd-deploy')())
  File "/home/zaterio/proyectos/isp/python3/bin/scrapyd-deploy", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zaterio/proyectos/isp/python3/lib/python3.9/site-packages/scrapyd_client/deploy.py", line 23, in <module>
    from scrapy.utils.http import basic_auth_header
ModuleNotFoundError: No module named 'scrapy.utils.http'
```

```

python -V
Python 3.9.5
```

**Comment by iamumairayub** [comment]
See this https://github.com/scrapy/scrapyd-client/issues/75#issuecomment-850156732

**Comment by mxdev88** [comment]
Hi, 3 PRs for the same issue. #68 #73 and #76 @redapple it would be great if it could be fixed. thks

**Comment by redapple** [comment]
@mxdev88 , I won't be able to help here. I having contributed to the scrapy ecosystem for several years now.
I suggest you contact the current maintainers.

**Comment by mxdev88** [comment]
> 
> 
> @mxdev88 , I won't be able to help here. I having contributed to the scrapy ecosystem for several years now.
> I suggest you contact the current maintainers.

ok sorry, just noticed you've been been most recent merging PRs to the repo. maybe @kmike @pablohoffman would you be able to help here pls? unsure who has write access to the repo and could help.

**Comment by 9776887181** [comment]
1、git clone https://github.com/scrapy/scrapyd-client.git
2、edit file  scrapyd_client/deploy.py
```
   #from scrapy.utils.http import basic_auth_header
   from w3lib.http import basic_auth_heade
```
3 、python3 setup.py install
